name: stayease_modern
description: Modern hotel booking UI (Light + Dark) scaffold.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.3
  intl: ^0.18.0
  flutter_animate: ^4.0.0
  flutter_staggered_grid_view: ^0.6.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/hotels.json
    - assets/data/tours.json
